spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/authenticate
    password: ''
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'