server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/authenticate
    password: ''
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: 'update'
    show-sql: 'true'
server:
  error:
    include-message: always
